### ISSUE TITLE
Ticker resource intensive on some machines

### ISSUE THREAD

**Issue by Goofybud16** [matty-r/urChat#32]
On my tablet, the Ticker runs slowly and uses a lot of resources. The tablet has:

Java 8,
Windows 8.1,
Intel Atom Dual Core 1.8GHz,
2GB Ram

(Lenovo Thinkpad Tablet 2)

Yet on my desktop, it runs fine.

Desktop: 
OpenJDK Java 7,
Debian Linux (Jessie),
Pentium Dual CPU E2140 @ 1.6GHz,
GTX 660 2GB,
2GB RAM

**Comment by matty-r** [comment]
Can be toggled off if that's an issue.
